source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

abstract_target 'HoroscopeAbstract' do
	
	pod 'SFRoundProgressCounterView', path: '../'
	
	target 'TestSFRoundProgressCounterView' do
	end
	
end